<?php
/**
* CC-Marketplace - Classified Ads for Joomla!
*
* @package	CC-Marketplace
* @author	Lucas Huber (development@cc-hub.org)
* @copyright	Copyright (C) 2012-2012 CC-HUB.ORG, All rights reserved.
* @link		http://www.cc-hub.org
* @license	http://www.gnu.org/licenses/gpl-2.0.html GNU/GPL
* @description  CCMarketplace coded by Jextn.com based on Marketplace by Codingfish
*/
?>

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

CC-Marketplace includes or is derivative of works distributed under GPL license.
The full text for the GPL license can be found in the LICENSE.php file.
The original copyright notices have been preserved within the respective files and or packages.  Please refer to the specific files and/or packages for more detailed information about the authors, copyrights, and licenses.
---------------------------------------------------------------------------------------------
